name: Multi-OpenWrt Images
  
on:
  workflow_dispatch:
    inputs:
      INPUT_TARGET:
        description: "Target to build (platform/target/subtarget)"
        required: false
        default: "all"
  push:
    paths: 
      - '.github/workflows/release.yml'
      
env:
  TZ: Asia/Shanghai
  # ä¸‹è½½çº¿ç¨‹æ•° DOWNLOAD
  DOWNLOAD: 8
  # ç¼–è¯‘æ ¸å¿ƒæ•° 0 é»˜è®¤æœ€å¤š
  NPROC: 0
  # æž„å»ºåŽŸç‰ˆUboot
  Vanilla: true
  # çŽ¯å¢ƒ true
  ENVIRONMENT: true
  # å¿«é€Ÿç¼–è¯‘
  FAST: true
  # å¼€å¯SSH
  SSH: tru 
  # å¼€å¯SSH åŽŸåŽ‚å›ºä»¶
  VanillaUboot: true
  # ç¼–è¯‘æ’ä»¶ç‰ˆ   
  PLUGINver: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - name: Generate release tag
      id: tag
    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      #  [ $UPLOAD_COWTRANSFER = true ] && echo "ðŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
     #   [ $UPLOAD_WETRANSFER = true ] && echo "ðŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d)"
        touch release.txt 
        echo "ðŸ”— [Cowtransfer]" >> release.txt
        echo "ðŸ”— [WeTransfer]" >> release.txt
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: release.txt
